# name: Build and Release

# on:
#   pull_request:
#     branches:
#       - master
#     tags-ignore:
#       - "**"
#     paths-ignore:
#       - ".gitignore"
#       - "**.md"
#       - "**.yml"
#       - "**.png"
# # on:
# #   release:
# #     types: [published]

# jobs:
#   build:
#     runs-on: macos-11

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v1

#       - name: Set output
#         run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

#       - name: Download Provisioning Profiles
#         id: provisioning
#         uses: apple-actions/download-provisioning-profiles@v1
#         with:
#           bundle-id: com.inderdhir.DatWeatherDoe
#           profile-type: "MAC_APP_DIRECT"
#           issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
#           api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
#           api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

#       - name: Build app
#         run: | 
#           sudo xcode-select -switch /Applications/Xcode_13.0.app
#           xcodebuild -scheme "DatWeatherDoe" clean archive -archivePath app.xcarchive

#       # - name: Notarize archive
#       #   env:
#       #     APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
#       #   run: |
#       #     xcodebuild -exportArchive -archivePath app.xcarchive -exportPath "DatWeatherDoe-$GITHUB_ENV.app" -exportOptionsPlist exportOptions.plist

#       # - name: Install DMG creator
#       #   run: |
#       #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#       #     brew install create-dmg

#       # - name: Notarize app
#       #   run: |
#       #     create-dmg "DatWeatherDoe-$GITHUB_ENV.dmg" .

#       #     echo $APPSTORE_PRIVATE_KEY >> key.p8
#       #     xcrun notarytool submit "DatWeatherDoe-$GITHUB_ENV.dmg" --wait --key "./key.p8" --key-id $APPSTORE_KEY_ID --issuer $APPSTORE_ISSUER_ID
