name: Tests

on:
   pull_request:
     branches:
       - master

jobs:
  tests:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Restore cached Swift Packages
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-sp-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-sp-

    - name: Run unit tests
      run: |
        sudo xcode-select --switch /Applications/Xcode_13.2.1.app
        
        xcodebuild clean test -scheme "DatWeatherDoe"