name: Test

on:
  pull_request:
    branches:
      - master
    tags-ignore:
      - "**"
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "**.yml"
      - "**.png"

jobs:
  run-tests:
    runs-on: macos-11
    env:
      DATWEATHERDOE_BUNDLE_ID: ${{ secrets.DATWEATHERDOE_BUNDLE_ID }}
      DATWEATHERDOE_FASTLANE_MATCH_URL: ${{ secrets.DATWEATHERDOE_FASTLANE_MATCH_URL }}
      DATWEATHERDOE_FASTLANE_USER: ${{ secrets.DATWEATHERDOE_FASTLANE_USER }}
      MATCH_REPO_DEPLOY_KEY: ${{ secrets.MATCH_REPO_DEPLOY_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup access to Fastlane Match repo
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.MATCH_REPO_DEPLOY_KEY }}"

      - name: Setup signing
        run: |
          bundle install
          bundle exec fastlane match development

      - name: Run unit tests
        run: |
          sudo xcode-select -switch /Applications/Xcode_13.0.app
          xcodebuild clean test -scheme "DatWeatherDoe"
